/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nitestay;

import com.lowagie.text.Document;
import com.lowagie.text.DocumentException;
import com.lowagie.text.Font;
import com.lowagie.text.Paragraph;
import com.lowagie.text.pdf.PdfPTable;
import com.lowagie.text.pdf.PdfWriter;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.text.SimpleDateFormat;
import java.time.Duration;
import java.time.LocalDate;
import java.time.temporal.ChronoUnit;
import java.util.ArrayList;
import java.util.Date;
import java.util.Locale;
import java.util.Properties;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.activation.DataHandler;
import javax.activation.DataSource;
import javax.activation.FileDataSource;
import javax.mail.BodyPart;

import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.Multipart;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeBodyPart;
import javax.mail.internet.MimeMessage;
import javax.mail.internet.MimeMultipart;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.Timer;

/**
 *
 * @author Ceruleaf
 */
public class HomeView extends javax.swing.JFrame {
    
    int jumlahkamar = 0;
    boolean isName = false;
    String username2 = "admin2 lol";

    /**
     * Creates new form HomeView
     */
    public HomeView() {
        initComponents();
    }

    void showDate() {
        Date currentdate = new Date();
        SimpleDateFormat s = new SimpleDateFormat("yyyy-MM-dd");
        timeaus2.setText(s.format(currentdate));
    }

    void showTime() {
        new Timer(0, new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                Date d = new Date();
                SimpleDateFormat s = new SimpleDateFormat("hh:mm:ss");
                timeaus.setText(s.format(d));
            }

        }).start();
    }

    public HomeView(String username) {
        
        //ArrayList<String> roomnumber = new ArrayList<String>();
        initComponents();
        
        showDate();
        showTime();
        roomoptionpanel.setVisible(false);
        summarypanel.setVisible(false);
        
        Image icon = Toolkit.getDefaultToolkit().getImage("src/logo/NightStaylogo.png");
        setIconImage(icon);
        setTitle("NightStayPlanner");

    }

    void send_mail() {
        String Email1 = "ihsanshiddiq6513@gmail.com";
        String Email2 = "alif.zaky.c@students.esqbs.ac.id";

        String from = "nightstay165@gmail.com";
        final String username = "nightstay165@gmail.com";
        final String password = "Esqbs165*";
        String host = "smtp.gmail.com";

        Properties props = new Properties();
        props.put("mail.smtp.auth", "true");
        props.put("mail.smtp.starttls.enable", "true");
        props.put("mail.smtp.host", host);
        props.put("mail.smtp.port", "587");

        Session session = Session.getInstance(props, new javax.mail.Authenticator() {
            @Override
            protected PasswordAuthentication getPasswordAuthentication() {
                return new PasswordAuthentication(username, password);
            }
        });

        try {
            Message message = new MimeMessage(session);
            message.setFrom(new InternetAddress(from));

            message.setRecipients(Message.RecipientType.TO, InternetAddress.parse(Email1));
            message.setRecipients(Message.RecipientType.CC, InternetAddress.parse(Email2));

            message.setSubject("Repport File");

            message.setText(ReportTextArea.getText());

            Transport.send(message);

            System.out.println("Sent message successfully....");
            
            JOptionPane.showMessageDialog(null, "Sent successfully");

        } catch (MessagingException e) {
            throw new RuntimeException(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        aboutframe = new javax.swing.JDialog();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        aboutpanel = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        btnContact = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        report_panel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ReportTextArea = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        SendRepport_Button = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        emailsentnotification = new javax.swing.JDialog();
        jLabel3 = new javax.swing.JLabel();
        btnHome = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        leftsidehomepanel = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        btnAbout = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        timeaus = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        timeaus2 = new javax.swing.JLabel();
        helperlabel = new javax.swing.JPanel();
        lblcurrentpanel = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        registerpanel = new javax.swing.JPanel();
        nextbtnregisterpanel = new javax.swing.JButton();
        gendercombobox = new javax.swing.JComboBox<>();
        firstnameinput = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lastnameinput = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        emailinput = new javax.swing.JTextField();
        roomoptionpanel = new javax.swing.JPanel();
        backbtnroomoptionpanel = new javax.swing.JButton();
        nextbtnroomoptionpanel = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        roomtype = new javax.swing.JComboBox<>();
        checkin = new com.toedter.calendar.JDateChooser();
        checkout = new com.toedter.calendar.JDateChooser();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        lblroomoptionpanelsummary1 = new javax.swing.JLabel();
        lblroomoptionpanelsummary2 = new javax.swing.JLabel();
        lblroomoptionpanelsummary3 = new javax.swing.JLabel();
        lblroomoptionpanelsummary4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        summarypanel = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        backbtnsummarypanel = new javax.swing.JButton();
        btnSummarySend = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        finalroom = new javax.swing.JLabel();
        finalduration = new javax.swing.JLabel();
        finalroomprice = new javax.swing.JLabel();
        finalprice = new javax.swing.JLabel();
        finalroomprice2 = new javax.swing.JLabel();
        finalroomprice3 = new javax.swing.JLabel();
        terbayarconfirm = new javax.swing.JCheckBox();

        aboutpanel.setBackground(new java.awt.Color(102, 102, 102));

        jLabel11.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Version v0.8");

        jLabel13.setFont(new java.awt.Font("DialogInput", 2, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Copyright 2020 © All rights reserved.");

        jLabel14.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Author");

        jLabel15.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Supported by Google");

        btnContact.setFont(new java.awt.Font("DialogInput", 0, 14)); // NOI18N
        btnContact.setText("Contact Us");
        btnContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContactActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("DialogInput", 0, 48)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("> M.Ihsan");

        jLabel17.setFont(new java.awt.Font("DialogInput", 0, 48)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("> Ceruleaf");

        javax.swing.GroupLayout aboutpanelLayout = new javax.swing.GroupLayout(aboutpanel);
        aboutpanel.setLayout(aboutpanelLayout);
        aboutpanelLayout.setHorizontalGroup(
            aboutpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aboutpanelLayout.createSequentialGroup()
                .addGroup(aboutpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(aboutpanelLayout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(btnContact))
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addComponent(jLabel15))
            .addGroup(aboutpanelLayout.createSequentialGroup()
                .addGroup(aboutpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(aboutpanelLayout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(aboutpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17)))
                    .addGroup(aboutpanelLayout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(jLabel11))
                    .addGroup(aboutpanelLayout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(jLabel14)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        aboutpanelLayout.setVerticalGroup(
            aboutpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aboutpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addComponent(jLabel14)
                .addGap(27, 27, 27)
                .addComponent(jLabel16)
                .addGap(4, 4, 4)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnContact)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(aboutpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel15)))
        );

        ReportTextArea.setColumns(20);
        ReportTextArea.setRows(5);
        jScrollPane1.setViewportView(ReportTextArea);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("Report a bug or send us a feedback below");

        SendRepport_Button.setText("Send");
        SendRepport_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SendRepport_ButtonActionPerformed(evt);
            }
        });

        jButton8.setText("<< Back");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout report_panelLayout = new javax.swing.GroupLayout(report_panel);
        report_panel.setLayout(report_panelLayout);
        report_panelLayout.setHorizontalGroup(
            report_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(report_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(report_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(report_panelLayout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addGap(106, 106, 106))
                    .addGroup(report_panelLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(0, 142, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, report_panelLayout.createSequentialGroup()
                        .addComponent(jButton8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(SendRepport_Button)))
                .addContainerGap())
        );
        report_panelLayout.setVerticalGroup(
            report_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(report_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(report_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SendRepport_Button)
                    .addComponent(jButton8))
                .addContainerGap())
        );

        jLayeredPane2.setLayer(aboutpanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(report_panel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane2Layout = new javax.swing.GroupLayout(jLayeredPane2);
        jLayeredPane2.setLayout(jLayeredPane2Layout);
        jLayeredPane2Layout.setHorizontalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 496, Short.MAX_VALUE)
            .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(aboutpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(report_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPane2Layout.setVerticalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 332, Short.MAX_VALUE)
            .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(aboutpanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(report_panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout aboutframeLayout = new javax.swing.GroupLayout(aboutframe.getContentPane());
        aboutframe.getContentPane().setLayout(aboutframeLayout);
        aboutframeLayout.setHorizontalGroup(
            aboutframeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane2, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        aboutframeLayout.setVerticalGroup(
            aboutframeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane2, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setText("Email Telah Terkirim");

        btnHome.setText("Home");
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout emailsentnotificationLayout = new javax.swing.GroupLayout(emailsentnotification.getContentPane());
        emailsentnotification.getContentPane().setLayout(emailsentnotificationLayout);
        emailsentnotificationLayout.setHorizontalGroup(
            emailsentnotificationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, emailsentnotificationLayout.createSequentialGroup()
                .addContainerGap(56, Short.MAX_VALUE)
                .addGroup(emailsentnotificationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel3)
                    .addGroup(emailsentnotificationLayout.createSequentialGroup()
                        .addComponent(btnHome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnExit)))
                .addGap(52, 52, 52))
        );
        emailsentnotificationLayout.setVerticalGroup(
            emailsentnotificationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(emailsentnotificationLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel3)
                .addGap(32, 32, 32)
                .addGroup(emailsentnotificationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExit)
                    .addComponent(btnHome))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        leftsidehomepanel.setBackground(new java.awt.Color(0, 102, 102));

        jButton3.setText("Logout");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        btnAbout.setText("About");
        btnAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAboutActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nitestay");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Planner");

        timeaus.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        timeaus.setForeground(new java.awt.Color(255, 255, 255));
        timeaus.setText("[DATE & TIME]");

        jLabel5.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Organize Easily");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 8)); // NOI18N
        jLabel6.setText("__________________");

        timeaus2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        timeaus2.setForeground(new java.awt.Color(255, 255, 255));
        timeaus2.setText("[DATE & TIME]");

        javax.swing.GroupLayout leftsidehomepanelLayout = new javax.swing.GroupLayout(leftsidehomepanel);
        leftsidehomepanel.setLayout(leftsidehomepanelLayout);
        leftsidehomepanelLayout.setHorizontalGroup(
            leftsidehomepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftsidehomepanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(leftsidehomepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, leftsidehomepanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(leftsidehomepanelLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(leftsidehomepanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(leftsidehomepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnAbout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(leftsidehomepanelLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(leftsidehomepanelLayout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(leftsidehomepanelLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(leftsidehomepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(timeaus)
                            .addComponent(timeaus2))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        leftsidehomepanelLayout.setVerticalGroup(
            leftsidehomepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, leftsidehomepanelLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(timeaus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(timeaus2)
                .addGap(30, 30, 30)
                .addComponent(btnAbout)
                .addGap(29, 29, 29)
                .addComponent(jButton3)
                .addGap(39, 39, 39))
        );

        helperlabel.setBackground(new java.awt.Color(0, 102, 51));

        lblcurrentpanel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblcurrentpanel.setForeground(new java.awt.Color(255, 255, 255));
        lblcurrentpanel.setText("FORM IDENTITAS PELANGGAN");

        javax.swing.GroupLayout helperlabelLayout = new javax.swing.GroupLayout(helperlabel);
        helperlabel.setLayout(helperlabelLayout);
        helperlabelLayout.setHorizontalGroup(
            helperlabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(helperlabelLayout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(lblcurrentpanel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        helperlabelLayout.setVerticalGroup(
            helperlabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(helperlabelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblcurrentpanel, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLayeredPane1.setBackground(new java.awt.Color(255, 153, 153));

        registerpanel.setBackground(new java.awt.Color(0, 102, 153));

        nextbtnregisterpanel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nextbtnregisterpanel.setText("Next>>");
        nextbtnregisterpanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextbtnregisterpanelActionPerformed(evt);
            }
        });

        gendercombobox.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        gendercombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laki laki", "Perempuan" }));
        gendercombobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gendercomboboxActionPerformed(evt);
            }
        });

        firstnameinput.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("First Name");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Last Name");

        lastnameinput.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Gender");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Email");

        emailinput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailinputActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout registerpanelLayout = new javax.swing.GroupLayout(registerpanel);
        registerpanel.setLayout(registerpanelLayout);
        registerpanelLayout.setHorizontalGroup(
            registerpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registerpanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(nextbtnregisterpanel)
                .addGap(21, 21, 21))
            .addGroup(registerpanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(registerpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(registerpanelLayout.createSequentialGroup()
                        .addGroup(registerpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel9)
                            .addComponent(jLabel7)
                            .addComponent(firstnameinput, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                            .addComponent(jLabel8)
                            .addComponent(lastnameinput, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                            .addComponent(gendercombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(registerpanelLayout.createSequentialGroup()
                        .addGroup(registerpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(emailinput, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 346, Short.MAX_VALUE))))
        );
        registerpanelLayout.setVerticalGroup(
            registerpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registerpanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(firstnameinput, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lastnameinput, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(emailinput, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(gendercombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(nextbtnregisterpanel)
                .addGap(25, 25, 25))
        );

        roomoptionpanel.setBackground(new java.awt.Color(0, 153, 153));

        backbtnroomoptionpanel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        backbtnroomoptionpanel.setText("<< Back");
        backbtnroomoptionpanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnroomoptionpanelActionPerformed(evt);
            }
        });

        nextbtnroomoptionpanel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        nextbtnroomoptionpanel.setText("Next");
        nextbtnroomoptionpanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextbtnroomoptionpanelActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Jenis kamar");

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Lama tinggal");

        roomtype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Deluxe", "Suite", "Junior Suite", "President Suite" }));
        roomtype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomtypeActionPerformed(evt);
            }
        });

        checkin.setDateFormatString("yyyy-MM-dd");

        checkout.setDateFormatString("yyyy-MM-dd");

        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Check In");

        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Check Out");

        lblroomoptionpanelsummary1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblroomoptionpanelsummary1.setForeground(new java.awt.Color(255, 255, 255));
        lblroomoptionpanelsummary1.setText("Deluxe - Rp5");

        lblroomoptionpanelsummary2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblroomoptionpanelsummary2.setForeground(new java.awt.Color(255, 255, 255));
        lblroomoptionpanelsummary2.setText("Suite - Rp4");

        lblroomoptionpanelsummary3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblroomoptionpanelsummary3.setForeground(new java.awt.Color(255, 255, 255));
        lblroomoptionpanelsummary3.setText("Junior Suite - Rp7");

        lblroomoptionpanelsummary4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblroomoptionpanelsummary4.setForeground(new java.awt.Color(255, 255, 255));
        lblroomoptionpanelsummary4.setText("President Suite - Rp8");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "101", "102", "103", "104" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout roomoptionpanelLayout = new javax.swing.GroupLayout(roomoptionpanel);
        roomoptionpanel.setLayout(roomoptionpanelLayout);
        roomoptionpanelLayout.setHorizontalGroup(
            roomoptionpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roomoptionpanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(roomoptionpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roomoptionpanelLayout.createSequentialGroup()
                        .addGroup(roomoptionpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(roomoptionpanelLayout.createSequentialGroup()
                                .addGroup(roomoptionpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(roomtype, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(roomoptionpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblroomoptionpanelsummary2)
                                    .addComponent(lblroomoptionpanelsummary1)
                                    .addComponent(lblroomoptionpanelsummary4)
                                    .addComponent(lblroomoptionpanelsummary3)))
                            .addGroup(roomoptionpanelLayout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(roomoptionpanelLayout.createSequentialGroup()
                                .addGroup(roomoptionpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(checkin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel18))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(roomoptionpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel20)
                                    .addComponent(checkout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(75, 75, 75))
                    .addGroup(roomoptionpanelLayout.createSequentialGroup()
                        .addComponent(backbtnroomoptionpanel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(nextbtnroomoptionpanel, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28))))
        );
        roomoptionpanelLayout.setVerticalGroup(
            roomoptionpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roomoptionpanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(roomoptionpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(lblroomoptionpanelsummary1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(roomoptionpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(roomtype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblroomoptionpanelsummary2))
                .addGroup(roomoptionpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(roomoptionpanelLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(roomoptionpanelLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(lblroomoptionpanelsummary3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblroomoptionpanelsummary4)))
                .addGap(34, 34, 34)
                .addComponent(jLabel19)
                .addGap(18, 18, 18)
                .addGroup(roomoptionpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(roomoptionpanelLayout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(checkin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(roomoptionpanelLayout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(checkout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                .addGroup(roomoptionpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backbtnroomoptionpanel)
                    .addComponent(nextbtnroomoptionpanel))
                .addGap(24, 24, 24))
        );

        summarypanel.setBackground(new java.awt.Color(0, 51, 51));
        summarypanel.setPreferredSize(new java.awt.Dimension(532, 366));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Jenis Kamar");

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Durasi tinggal");

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Kamar/malam");

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("SUMMARY");

        backbtnsummarypanel.setText("Back");
        backbtnsummarypanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnsummarypanelActionPerformed(evt);
            }
        });

        btnSummarySend.setText("Send to Email");
        btnSummarySend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSummarySendActionPerformed(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Total");

        finalroom.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        finalroom.setForeground(new java.awt.Color(255, 255, 255));
        finalroom.setText(": x");

        finalduration.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        finalduration.setForeground(new java.awt.Color(255, 255, 255));
        finalduration.setText(": x");

        finalroomprice.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        finalroomprice.setForeground(new java.awt.Color(255, 255, 255));
        finalroomprice.setText(": x/malam");

        finalprice.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        finalprice.setForeground(new java.awt.Color(255, 255, 255));
        finalprice.setText(": x");

        finalroomprice2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        finalroomprice2.setForeground(new java.awt.Color(255, 255, 255));
        finalroomprice2.setText("________________");

        finalroomprice3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        finalroomprice3.setForeground(new java.awt.Color(255, 255, 255));
        finalroomprice3.setText("________________");

        terbayarconfirm.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        terbayarconfirm.setForeground(new java.awt.Color(0, 255, 0));
        terbayarconfirm.setText("Terbayar");
        terbayarconfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                terbayarconfirmActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout summarypanelLayout = new javax.swing.GroupLayout(summarypanel);
        summarypanel.setLayout(summarypanelLayout);
        summarypanelLayout.setHorizontalGroup(
            summarypanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(summarypanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(summarypanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, summarypanelLayout.createSequentialGroup()
                        .addComponent(backbtnsummarypanel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 303, Short.MAX_VALUE)
                        .addComponent(btnSummarySend)
                        .addGap(34, 34, 34))
                    .addGroup(summarypanelLayout.createSequentialGroup()
                        .addGroup(summarypanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(summarypanelLayout.createSequentialGroup()
                                .addGroup(summarypanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel21)
                                    .addComponent(jLabel22)
                                    .addComponent(jLabel23))
                                .addGap(35, 35, 35)
                                .addGroup(summarypanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(finalduration)
                                    .addComponent(finalroom)
                                    .addComponent(finalroomprice)
                                    .addGroup(summarypanelLayout.createSequentialGroup()
                                        .addComponent(finalprice)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(terbayarconfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabel24))
                        .addGap(55, 55, 55))
                    .addGroup(summarypanelLayout.createSequentialGroup()
                        .addGroup(summarypanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(summarypanelLayout.createSequentialGroup()
                                .addGap(142, 142, 142)
                                .addComponent(finalroomprice3))
                            .addComponent(finalroomprice2)
                            .addComponent(jLabel25))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        summarypanelLayout.setVerticalGroup(
            summarypanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(summarypanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel24)
                .addGap(18, 18, 18)
                .addGroup(summarypanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(finalroom))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(summarypanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(finalduration))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(summarypanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(finalroomprice))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(summarypanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(finalroomprice2)
                    .addComponent(finalroomprice3))
                .addGap(19, 19, 19)
                .addGroup(summarypanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(finalprice)
                    .addComponent(terbayarconfirm))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 118, Short.MAX_VALUE)
                .addGroup(summarypanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backbtnsummarypanel)
                    .addComponent(btnSummarySend))
                .addGap(23, 23, 23))
        );

        jLayeredPane1.setLayer(registerpanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(roomoptionpanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(summarypanel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(registerpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(roomoptionpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(summarypanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(registerpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(roomoptionpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(summarypanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(leftsidehomepanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(helperlabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLayeredPane1)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(leftsidehomepanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(helperlabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLayeredPane1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void terbayarconfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_terbayarconfirmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_terbayarconfirmActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        firstnameinput.setText("");
        lastnameinput.setText("");
        emailinput.setText("");
        checkin.setCalendar(null);
        checkout.setCalendar(null);
        registerpanel.setVisible(true);
        roomoptionpanel.setVisible(false);
        summarypanel.setVisible(false);
        emailsentnotification.setVisible(false);

// TODO add your handling code here:
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        System.exit(0);
// TODO add your handling code here:
    }//GEN-LAST:event_btnExitActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton3ActionPerformed

        LoginView login = new LoginView(username2);
        login.setLocationRelativeTo(null);
        login.setVisible(true);
        this.setVisible(false);

        // TODO add your handling code here:
    }// GEN-LAST:event_jButton3ActionPerformed

    private void backbtnsummarypanelActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_backbtnsummarypanelActionPerformed
        summarypanel.setVisible(false);
        roomoptionpanel.setVisible(true);
        lblcurrentpanel.setText("RENCANA TINGGAL");
        // TODO add your handling code here:
    }// GEN-LAST:event_backbtnsummarypanelActionPerformed

    private void btnSummarySendActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnSummarySendActionPerformed
        // TODO add your handling code here:
        String checkinattempt = ((JTextField) checkin.getDateEditor().getUiComponent()).getText();
        String checkoutattempt = ((JTextField) checkout.getDateEditor().getUiComponent()).getText();

        LocalDate chkinday = LocalDate.parse(checkinattempt);
        LocalDate chkoutday = LocalDate.parse(checkoutattempt);

        Long day_gap = ChronoUnit.DAYS.between(chkinday, chkoutday);
        
        String fname1 = firstnameinput.getText();
        String fname = fname1.toUpperCase();
        String lname1 = lastnameinput.getText();
        String lname = lname1.toUpperCase();
        
        String roomprint = roomtype.getSelectedItem().toString();
        String room_numprint = jComboBox1.getSelectedItem().toString();
        
        String res = null;
        boolean paid = terbayarconfirm.isSelected();
        if (paid == true) {
            res = "Sudah dibayar.";
        } else {
            res = "Belum dibayar.";
        }
        
        String gender = gendercombobox.getSelectedItem().toString();
        String panggilan = null;
        switch(gender){
            case "Laki laki":
                panggilan = "TN. ";
                break;
            case "Perempuan":
                panggilan = "NY. ";
                break;
            default:
                panggilan = null;
                break;
        }
        
        int stayprice = 0;
        switch (roomprint) {
            case "Deluxe":
                stayprice = 5;
                break;
            case "Suite":
                stayprice = 4;
                break;
            case "Junior Suite":
                stayprice = 7;
                break;
            case "President Suite":
                stayprice = 8;
                break;
            default:
                break; 
        }
        
        int finaltotal = (int) (day_gap * stayprice);
        
        String path = "\\Users\\Public\\Documents";
        
        //nama file
        String nameFile = fname + lname + "invoice";
        
        Document doc = new Document();
        
        try {
            PdfWriter.getInstance(doc, new FileOutputStream(path+ "\\" + nameFile + ".pdf"));
            doc.open();
            
            PdfPTable tbl = new PdfPTable(5 );
            Paragraph para = new Paragraph();
            
           
            //
            Font catFont = new Font(null, 24, Font.BOLD);
            Font fnameprint = new Font(null, 20, Font.BOLD);
            Font lnameprint = new Font(null, 18);
            Font desc = new Font(null,16);
            //title setting
            para.add(new Paragraph("NIGHTSTAY INVOICE", catFont));
            para.add(new Paragraph("_________________", catFont));
            para.add(new Paragraph(""));
            para.add(new Paragraph(panggilan + fname, fnameprint));
            para.add(new Paragraph(lname,lnameprint));
            para.add(new Paragraph(""));
            para.add(new Paragraph("Kamar :  " + roomprint + " " + room_numprint, desc));
            para.add(new Paragraph("Durasi Tinggal :  " + day_gap + " Hari", desc));
            para.add(new Paragraph("Harga Kamar :  Rp" + stayprice + " /malam", desc));
            para.add(new Paragraph("Check In :  " + chkinday, desc));
            para.add(new Paragraph("Check Out :  " + chkoutday, desc));
            para.add(new Paragraph(""));
            para.add(new Paragraph("TOTAL: Rp" + finaltotal, fnameprint));
            para.add(new Paragraph("Status: " + res, desc));
            
            //table setting
            //adding header
            
            
            doc.add(para);
            //doc.add(tbl);

        } catch (FileNotFoundException ex) {
            Logger.getLogger(HomeView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (DocumentException ex) {
            Logger.getLogger(HomeView.class.getName()).log(Level.SEVERE, null, ex);
        }

        doc.close();

        JOptionPane.showMessageDialog(null, "File created.");

        // ===================================================
        // ==========BELOW IS SEND TO EMAIL FUNCTION==========
        // ===================================================

        String to = emailinput.getText();

        String from = "nightstay165@gmail.com";
        final String username = "nightstay165@gmail.com";
        final String password = "Esqbs165*";
        String host = "smtp.gmail.com";

        Properties props = new Properties();
        props.put("mail.smtp.auth", "true");
        props.put("mail.smtp.starttls.enable", "true");
        props.put("mail.smtp.host", host);
        props.put("mail.smtp.port", "587");

        Session session = Session.getInstance(props, new javax.mail.Authenticator() {
            @Override
            protected PasswordAuthentication getPasswordAuthentication() {
                return new PasswordAuthentication(username, password);
            }
        });
        
        Boolean flag = true;

        try {
            Message message = new MimeMessage(session);
            message.setFrom(new InternetAddress(from));
            message.setRecipients(Message.RecipientType.TO, InternetAddress.parse(to));

            message.setSubject("NIGHTSTAY INVOICE");

            BodyPart messageBodyPart = new MimeBodyPart();
            messageBodyPart.setText("Invoice for " + fname +" "+ lname);

            Multipart multipart = new MimeMultipart();
            multipart.addBodyPart(messageBodyPart);

            messageBodyPart = new MimeBodyPart();
            // String filename = "\\Users\\LeSnovo\\Documents\\Subject1.txt";
            String filename = "\\Users\\Public\\Documents\\" + nameFile + ".pdf";
            DataSource source = new FileDataSource(filename);
            messageBodyPart.setDataHandler(new DataHandler(source));
            messageBodyPart.setFileName("Night Stay Invoice.pdf");
            multipart.addBodyPart(messageBodyPart);

            message.setContent(multipart);

            Transport.send(message);

            System.out.println("Sent message successfully....");
            
            emailsentnotification.setVisible(true);
            emailsentnotification.setSize(340, 180);
            
        }catch (Exception e) {
            JOptionPane.showMessageDialog(null, "An Error occurred. Email not sent.",
                    "Error", JOptionPane.ERROR_MESSAGE);
            throw new RuntimeException(e);
        }
       
        
    }// GEN-LAST:event_btnSummarySendActionPerformed

    private void nextbtnregisterpanelActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_nextbtnregisterpanelActionPerformed
        String firstnameattempt = firstnameinput.getText();
        String lastnameattempt = lastnameinput.getText();
        String emailattempt = emailinput.getText();

        if (firstnameattempt.trim().isEmpty() || lastnameattempt.trim().isEmpty() || emailattempt.trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Error you did not enter a name/email properly, please try again.",
                    "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            isName = true;
            roomoptionpanel.setVisible(true);
            registerpanel.setVisible(false);
            lblcurrentpanel.setText("RENCANA TINGGAL");
        }

        // TODO add your handling code here:
    }// GEN-LAST:event_nextbtnregisterpanelActionPerformed

    private void gendercomboboxActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_gendercomboboxActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_gendercomboboxActionPerformed

    private void btnContactActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnContactActionPerformed
        // TODO add your handling code here:
        report_panel.setVisible(true);
        aboutpanel.setVisible(false);

    }// GEN-LAST:event_btnContactActionPerformed

    private void backbtnroomoptionpanelActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_backbtnroomoptionpanelActionPerformed
        roomoptionpanel.setVisible(false);
        registerpanel.setVisible(true);
        lblcurrentpanel.setText("FORM IDENTITAS PELANGGAN");

        // TODO add your handling code here:
    }// GEN-LAST:event_backbtnroomoptionpanelActionPerformed

    private void SendRepport_ButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_SendRepport_ButtonActionPerformed
        // TODO add your handling code here:
        send_mail();

    }// GEN-LAST:event_SendRepport_ButtonActionPerformed

    private void btnAboutActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnAboutActionPerformed
        // TODO add your handling code here:
        aboutframe.setVisible(true);
        aboutframe.setSize(500, 400);
        report_panel.setVisible(false);
    }// GEN-LAST:event_btnAboutActionPerformed

    private void emailinputActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_emailinputActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_emailinputActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton8ActionPerformed
        aboutpanel.setVisible(true);
        report_panel.setVisible(false);
        // TODO add your handling code here:
    }// GEN-LAST:event_jButton8ActionPerformed

    private void nextbtnroomoptionpanelActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_nextbtnroomoptionpanelActionPerformed
        String checkinattempt = ((JTextField) checkin.getDateEditor().getUiComponent()).getText();
        String checkoutattempt = ((JTextField) checkout.getDateEditor().getUiComponent()).getText();

        Date checkindate = checkin.getDate();
        Date checkoutdate = checkout.getDate();
        
        Date currentdate = new Date();
        SimpleDateFormat s = new SimpleDateFormat("yyyy-MM-dd");
        String crtdt = (s.format(currentdate));
        // LocalDate chkinday = LocalDate.parse(checkinattempt);
        // LocalDate chkoutday = LocalDate.parse(checkoutattempt);

        // Long day_gap = ChronoUnit.DAYS.between(chkinday, chkoutday);

        
        String room = roomtype.getSelectedItem().toString();
        String room_num = jComboBox1.getSelectedItem().toString();

        int[] StayPrice = { 5, 4, 7, 8 };

        int stayprice = 0;

        switch (room) {
            case "Deluxe":
                stayprice = StayPrice[0];

                break;
            case "Suite":
                stayprice = StayPrice[1];

                break;
            case "Junior Suite":
                stayprice = StayPrice[2];

                break;
            case "President Suite":
                stayprice = StayPrice[3];

                break;
            default:
                break;
        }

        if (!(checkindate == null) && !(checkoutdate == null)) {

            LocalDate chkinday = LocalDate.parse(checkinattempt);
            LocalDate chkoutday = LocalDate.parse(checkoutattempt);

            Long day_gap = ChronoUnit.DAYS.between(chkinday, chkoutday);

            if (!(day_gap <= 0) && !(checkindate.before(currentdate)) ) {
                int finaltotal = (int) (day_gap * stayprice);
                summarypanel.setVisible(true);
                roomoptionpanel.setVisible(false);
                finalroom.setText(": " + roomtype.getSelectedItem().toString() + "(" + room_num + ")");
                finalduration.setText(": " + String.valueOf(day_gap) + " hari");
                finalroomprice.setText(": Rp" + stayprice + " /malam");
                finalprice.setText(": Rp" + finaltotal);
                lblcurrentpanel.setText("CONFIRMATION");
            } else {
                JOptionPane.showMessageDialog(null, "Please input an appropriate date",
                        "Message!", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please input an appropriate date", "Message!",
                    JOptionPane.ERROR_MESSAGE);
        }
        // TODO add your handling code here:
    }// GEN-LAST:event_nextbtnroomoptionpanelActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jComboBox1ActionPerformed

    private void roomtypeActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_roomtypeActionPerformed
        // TODO add your handling code here:
        String room = roomtype.getSelectedItem().toString();
        try {
            switch (room) {
                case "Deluxe":
                    jComboBox1.removeAllItems();
                    jComboBox1.addItem("101");
                    jComboBox1.addItem("102");
                    jComboBox1.addItem("103");
                    jComboBox1.addItem("104");
                    break;
                case "Suite":
                    jComboBox1.removeAllItems();
                    jComboBox1.addItem("201");
                    jComboBox1.addItem("202");
                    jComboBox1.addItem("203");
                    jComboBox1.addItem("204");
                    break;
                case "Junior Suite":
                    jComboBox1.removeAllItems();
                    jComboBox1.addItem("301");
                    jComboBox1.addItem("302");
                    jComboBox1.addItem("303");
                    jComboBox1.addItem("304");
                    break;
                case "President Suite":
                    jComboBox1.removeAllItems();
                    jComboBox1.addItem("105");
                    jComboBox1.addItem("205");
                    jComboBox1.addItem("305");
                    break;
                default:
                    jComboBox1.removeAllItems();
                    break;
            }

        } catch (Exception e) {
            throw new RuntimeException(e);

        }

    }// GEN-LAST:event_roomtypeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea ReportTextArea;
    private javax.swing.JButton SendRepport_Button;
    private javax.swing.JDialog aboutframe;
    private javax.swing.JPanel aboutpanel;
    private javax.swing.JButton backbtnroomoptionpanel;
    private javax.swing.JButton backbtnsummarypanel;
    private javax.swing.JButton btnAbout;
    private javax.swing.JButton btnContact;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnSummarySend;
    private com.toedter.calendar.JDateChooser checkin;
    private com.toedter.calendar.JDateChooser checkout;
    private javax.swing.JTextField emailinput;
    private javax.swing.JDialog emailsentnotification;
    private javax.swing.JLabel finalduration;
    private javax.swing.JLabel finalprice;
    private javax.swing.JLabel finalroom;
    private javax.swing.JLabel finalroomprice;
    private javax.swing.JLabel finalroomprice2;
    private javax.swing.JLabel finalroomprice3;
    private javax.swing.JTextField firstnameinput;
    private javax.swing.JComboBox<String> gendercombobox;
    private javax.swing.JPanel helperlabel;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton8;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lastnameinput;
    private javax.swing.JLabel lblcurrentpanel;
    private javax.swing.JLabel lblroomoptionpanelsummary1;
    private javax.swing.JLabel lblroomoptionpanelsummary2;
    private javax.swing.JLabel lblroomoptionpanelsummary3;
    private javax.swing.JLabel lblroomoptionpanelsummary4;
    private javax.swing.JPanel leftsidehomepanel;
    private javax.swing.JButton nextbtnregisterpanel;
    private javax.swing.JButton nextbtnroomoptionpanel;
    private javax.swing.JPanel registerpanel;
    private javax.swing.JPanel report_panel;
    private javax.swing.JPanel roomoptionpanel;
    private javax.swing.JComboBox<String> roomtype;
    private javax.swing.JPanel summarypanel;
    private javax.swing.JCheckBox terbayarconfirm;
    private javax.swing.JLabel timeaus;
    private javax.swing.JLabel timeaus2;
    // End of variables declaration//GEN-END:variables
}
